version: '3.6'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres      
volumes:
  db_data:
